services:
  lab-cyber-academy:
    build: ./
    image: lab-cyber-academy/web-terminal:latest
    container_name: lab-cyber-academy
    volumes:
      - ./connection.toml:/root/connection.toml
    ports:
      - 9000:9000
